### ISSUE TITLE
the tutorial should mention to install the otree package

### ISSUE THREAD

**Issue by digitaldust** [chkgk/otree_vm_docs#1]
when installing python, and the env thereafter, it might be worth mentioning to install the otree package.

Also it's not really clear how to start/stop the prodserver.

**Comment by chkgk** [comment]
Hi Simone,

This was written back in 2018 for the very specific setup we had at Heidelberg University. We mimic Heroku deployments. That is, experimenters got their own account to push their code from git to the server. The git post-receive script then installed otree and its requirements in the virtual environment of that experimenter. The otree server was subsequently started from that virtual environment automatically (using supervisor).

As I am not in Heidelberg anymore, I have not kept this guide updated. I will mark it as deprecated. A lot has changed since then and I no longer support or recommend this deployment method.

Best,
Christian

**Comment by digitaldust** [comment]
thanks @chkgk, can you suggest an updated source? Is this: https://otree.readthedocs.io/en/latest/index.html 

the right one?

**Comment by chkgk** [comment]
Yes, definitely go with the official docs at [https://otree.readthedocs.io/en/latest/server/intro.html#](https://otree.readthedocs.io/en/latest/server/intro.html).

If you want, we can also have a call and talk about viable setups. That way I might be able to give better recommendations. E-Mail me at email@ckgk.de.
